### ISSUE TITLE
做的这么好的一个游戏，为什么不去上线呢？

### ISSUE THREAD

**Issue by klkxxy** [chrisYooh/ChrisPower#1]
好奇问问

**Comment by chrisYooh** [comment]
刚做出来时候上线了，后来不维护更新就被苹果下线了（应该一年不更新就会被下线）
作为个人娱乐，技术尝鲜还可以，不过作为游戏产品还有差距的，为开源做贡献咯：）

**Comment by klkxxy** [comment]
哈哈，原来如此。第一次见用oc写游戏，觉得略神奇。谢谢up主分享，学习学习。

**Comment by chrisYooh** [comment]
毕业设计的项目，修改了放到iOS上。
其他的游戏开发库本质上就是封装了游戏相关的渲染操作，并尽可能做了效率优化。底层上没啥差异的，都是持续渲染画画：）
